sudo: true
os: linux
language: d
d:
 - ldc
 - dmd-beta
 - dmd
branches:
  only:
    - master
env:
 - ARCH="x86_64"
before_install:
  - sudo apt-get install tor
script:
  - sleep 10
  - dub test --arch "$ARCH"